### ISSUE TITLE
各 section の共通コンポーネントを切り出したい

### ISSUE THREAD

**Issue by ko-noguchi** [tokiwanomori/homepage#7]
各 section の css がほぼコピペ。

例
```scss
.blog{
  padding: 40px 0;
  background-color: $black-background-color;
  text-align: center;
  color: white;
  .blog-heading{
    h2{
        display: inline-block;
        margin: 20px 0;
        color: black;
        background-color: $white-background-color;
        font-weight: normal;
        font-size: 35px;
    }
    p{
      font-size: 25px;
    }
  }
}

.techblog{
  padding: 40px 0;
  background-color: $white-background-color;
  text-align: center;
  color: black;
  .techblog-heading{
    h2{
        display: inline-block;
        margin: 20px 0;
        color: white;
        background-color: $black-background-color;
        font-weight: normal;
        font-size: 35px;
    }
    p{
      font-size: 25px;
    }
  }
}
```

@mixin かなにかを使って切り出したいけど（FLOCSS 的に）どうするのがグッドなのかわからんので分かる人お願いしたいです
